# Copied from: https://github.com/pyTooling/Actions/blob/main/with-post-step/action.yml
name: With post step

description: 'Generic JS Action to execute a main command and set a command as a post step.'

inputs:
  main:
    description: 'Main command/script.'
    required: true
  post:
    description: 'Post command/script.'
    required: true
  key:
    description: 'Name of the state variable used to detect the post step.'
    required: false
    default: POST
  ephemeralToken:
    description: 'Ephemeral GitHub Token to be revoked on the post step.'
    required: true

runs:
  using: 'node20'
  main: 'main.js'
  post: 'main.js'
