name: Get Ephemeral GitHub Token from CI Vault
description: 'Fetch an ephemeral GitHub token from Vault using OIDC authentication'

inputs:
  vault-instance:
    description: 'Vault instance to connect to (ci-prod or ci-dev)'
    required: true
  vault-role:
    description: 'Vault role to assume for GitHub token retrieval'
    required: false
    default: ''
  # skip-token-revoke:
  #   description: 'Revoke the Vault token on exit'
  #   default: false
outputs:
  token:
    description: GitHub App installation access token.
    value: ${{ steps.vault-action.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Set Vault Address
      shell: bash
      id: vault-address
      env:
        VAULT_INSTANCE: ${{ inputs.vault-instance }}
      run: |
        set -euo pipefail

        if [[ "$VAULT_INSTANCE" == "ci-dev" ]]; then
          echo "url=https://vault-ci.dev.elastic.dev" >> "$GITHUB_OUTPUT"
          echo "Vault address set to CI-DEV."
        elif [[ "$VAULT_INSTANCE" == "ci-prod" ]]; then
          echo "url=https://vault-ci-prod.elastic.dev" >> "$GITHUB_OUTPUT"
          echo "Vault address set to CI-PROD."
        else
          echo "::error title=Input Validation Failed::Invalid vault instance: $VAULT_INSTANCE. Must be 'ci-dev' or 'ci-prod'."
          exit 1
        fi

    - name: Retrieve GitHub Workflow Ref and generate Vault Role name (vault-role input overrides this if provided)
      shell: bash
      id: vault-role
      if: ${{ inputs.vault-role == '' }}
      run: |
        set -euo pipefail

        echo "Workflow ref: $GITHUB_WORKFLOW_REF"
        WORKFLOW_REF_BASE="${GITHUB_WORKFLOW_REF%@*}"
        echo "Workflow ref base for role generation: $WORKFLOW_REF_BASE"
        # Generate role name using SHA-256 hash of workflow ref base
        WORKFLOW_HASH=$(echo -n "$WORKFLOW_REF_BASE" | sha256sum | cut -c1-12)
        VAULT_ROLE="token-policy-$WORKFLOW_HASH"
        echo "Generated role name: $VAULT_ROLE"
        echo "role=$VAULT_ROLE" >> "$GITHUB_OUTPUT"

    - name: "Diagnostic: Log Final Vault Parameters"
      shell: bash
      env:
        VAULT_ADDR: ${{ steps.vault-address.outputs.url }}
        VAULT_ROLE: ${{ inputs.vault-role == '' && steps.vault-role.outputs.role || inputs.vault-role }}
      run: |
        echo "--- Vault Action Input Parameters ---"
        echo "VAULT_ADDR (URL): $VAULT_ADDR"
        echo "VAULT_ROLE: $VAULT_ROLE"
        echo "Vault Secrets Path Expected: github/token/$VAULT_ROLE"
        echo "-------------------------------------"

    - name: Request OIDC Token from GitHub
      shell: bash
      id: oidc
      run: |
        echo "OIDC_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=vault" | jq -r '.value')" >> $GITHUB_ENV

    - name: Install Vault CLI
      shell: bash
      run: |
        VAULT_VERSION="1.20.4"
        curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip" -o vault.zip
        unzip vault.zip
        sudo install vault /usr/local/bin/
        vault --version

    - name: Fetch GitHub Token from Vault with Retry
      id: vault-action
      shell: bash
      env:
        VAULT_ADDR: ${{ steps.vault-address.outputs.url }}
        VAULT_ROLE: ${{ inputs.vault-role == '' && steps.vault-role.outputs.role || inputs.vault-role }}
        JWT_TOKEN: ${{ steps.oidc.outputs.id_token }}
      run: |
        for i in {1..5}; do
          LOGIN_RESPONSE=$(curl -s --request POST \
            --data '{"jwt": "'"$OIDC_TOKEN"'", "role": "'"$VAULT_ROLE"'"}' \
            "$VAULT_ADDR/v1/auth/github-oidc/login")
          VAULT_TOKEN=$(echo $LOGIN_RESPONSE | jq -r '.auth.client_token')
          export VAULT_TOKEN
          GITHUB_TOKEN=$(vault read -field=token "github/token/$VAULT_ROLE") && break
          echo "Retry $i/5 failed, retrying in 5s..."
          # if the login or read failed, wait before retrying (max 25s total wait)
          sleep 5
        done
        echo "token=$GITHUB_TOKEN" >> "$GITHUB_OUTPUT"

    - name: Token status check
      shell: bash
      run: gh auth status
      env:
        GH_TOKEN: ${{ steps.vault-action.outputs.token }}
