name: Get Ephemeral GitHub Token from CI Vault
description: 'Fetch an ephemeral GitHub token from Vault using OIDC authentication'
inputs:
  vault-instance:
    description: 'Vault instance to connect to (ci-prod or ci-dev)'
    required: true
  vault-role:
    description: 'Vault role to assume for GitHub token retrieval. If not provided, it will be generated based on the workflow ref of the GH Action.'
    required: false
    default: ''
  revoke:
    description: 'If true, revoke the GitHub token on exit'
    required: false
    default: 'false'
outputs:
  token:
    description: GitHub App installation access token.
runs:
  using: 'node24'
  main: 'dist/main.js'
  post: 'dist/revoke.js'
