name: pre-commit

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/pre-commit@9e2226b8a321731893ff5165a6981ee6da0bb280 # v1
