name: pre-commit

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/pre-commit@45041d3e0b65acffa44f2e0f39e15aafc024d940 # v1
