name: pre-commit

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/pre-commit@7a81c19824a038f33daebc323875db70c8743d1a # v1
