name: test-fetch-github-token
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - './*'
      - '.github/workflows/test-fetch-github-token.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./fetch-github-token
        with:
          vault-instance: "ci-prod"
